### ISSUE TITLE
Comment marche le programme ?

### ISSUE THREAD

**Issue by Mioultigaming** [ttwthomas/js-miner#1]
Bonjour, je suis débutant en minage de crypto et je voudrais savoir comment marche le programe et où mes on son wallet bitcoin ?
Merci

**Comment by FRKFFR** [comment]
c'est plutot un test de minnig

**Comment by FRKFFR** [comment]
https://ttwthomas.github.io/js-miner/index2.html

**Comment by foxypiratecove37350** [comment]
Tu ne mine pas vraiment de la crypto avec ce programme, mais il t'indique seulement combien de problème mathématiques complexe ton matériel peut résoudre par seconde (h/s). Et si tu veux savoir comment fonctionne le programme, regarde juste le code source, c'est pas si compliqué.
